### ISSUE TITLE
Automatically find latest version

### ISSUE THREAD

**Issue by dicer** [krt16s/ffupdater#1]
How about switching from guessing the next major version to parsing the webpage and finding the latest version that is not alpha or beta? That would also solve the problem of minor version updates, which sometime do contain critical security fixes.

Would that be a pull request you would be willing to merge? Then I would start working on it.

**Comment by krt16s** [comment]
Sure, looks like a good idea. Just make sure it falls back to other "known working" solutions in case of unexpected results (e.g. if they changed the page).

**Comment by iainnicol** [comment]
Hi @dicer.  Is this something you're actively working on?  If you don't have the time to do this, I'm keen to do it myself.  But if you do have the time, I don't want to step on your toes.

**Comment by dicer** [comment]
No, I haven't started yet and am a bit busy. I'm happy to review stuff though and help when needed. So go ahead!

**Comment by iainnicol** [comment]
Good to know, thanks.  I know how easy it is to not be able to find the time...  But since I've asked that should motivate me.

**Comment by chriscroome** [comment]
I use a cut-down version of this code to get the latest desktop version https://gist.github.com/ruario/9672798 and compare it when what is installed using `--version`:

```bash
ARCH=$(uname -m)
if [[ "${ARCH}" = i?86 ]]; then
  ARCH="i686"
fi

LANG="en-GB"

SERVER="https://ftp.mozilla.org/pub/firefox"

WGET="wget --no-proxy -qO-"

LATEST_VERSION=$($WGET $SERVER/releases/latest/linux-$ARCH/$LANG/ | sed -nr 's|.*>firefox-(.*)\.tar\.bz2</a>.*|\1|p' | tail -n 1 )
```

Sorry I don't know Java enough to translate this from Bash...

**Comment by iainnicol** [comment]
Thanks Chris. That's indeed analogous to what needs done in Java.

TBH this should be quite straightforward (if you know Java). It's just a case of not procrastinating! But I promise to do it this weekend.

**Comment by krt16s** [comment]
Any progress so far?

Btw: I am aware that we currently have 42.0.2 available, but Mozilla fails to updated /latest/ as well.... https://archive.mozilla.org/pub/mobile/releases/latest/android-api-11/multi/ points (at the moment) still to 42.0.1

**Comment by iainnicol** [comment]
Yup, I've done some.  I got distracted by being busy, but I'll resume in earnest over the next few days.

It's a shame the `latest` symlink isn't being updated.  In fact, it looks like there's now been a v43, which isn't linked either.

The good news is I was also implementing another strategy: first, guess the current major version based upon a known release date and the 6 week release cycle.  Then do HTTP requests to directories such as <https://archive.mozilla.org/pub/mobile/releases/43.0/> and <https://archive.mozilla.org/pub/mobile/releases/43.1/>.  If it's a 404 then the version doesn't exist, but if it's a 200 then the version does exist.  With a few requests you can determine the exact latest version.

**Comment by iainnicol** [comment]
The other thought I had is that this change—determining the latest—isn't actually helpful on its own.  You're still best updating the app manually until the background service is implemented.

**Comment by krt16s** [comment]
Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1233399

**Comment by krt16s** [comment]
I think we can now rely on https://download.mozilla.org/?product=fennec-latest&os=android&lang=multi being always the latest version as suggested by https://archive.mozilla.org/pub/mobile/releases/latest/README.txt

**Comment by krt16s** [comment]
4329cd723dd0c7ff5d25570e6d5ecd8c66abdc8f should close this issue.  However, having the appropriated download url in the bookmarks might just be the better way. I still don't see a way to check for new versions without downloading latest and moving everything to a service is still an open issue as well.

**Comment by FriendFX** [comment]
Sorry for the noise on this closed issue, but couldn't one parse Mozilla's https://archive.mozilla.org/pub/mobile/releases/ page for the latest version?

Employing the following simple regular expression

    a href=\"/pub/mobile/releases/(\d+\.\d+)/\"

seems to find the current latest release (50.0) the https://download.mozilla.org/?product=fennec-latest&os=android&lang=multi link you're using downloads when clicked.

Of course, it is still a concern that the archive page could be out of date wrt. the actual latest release and/or Mozilla changes the archive page...

**Comment by krt16s** [comment]
Sure, could you open a pull request with the necessary changes?

**Comment by FriendFX** [comment]
@krt16s Just keep in mind that I consider myself an Android beginner... so I don't think I feel confident enough to convert the whole app to a background service any time soon.

Now that's out of the way, what *are* the "necessary" changes anyway? How should the app behave? At the moment, it seems it's just a button which starts the "download the latest version" intent. If we take the version number as I suggested from the Mozilla link, how would that change? 

 1. Should the button be disabled if the installed version matches the latest available? 
 2. Or should there be a separate button "check for updates" that runs that check first and then suggests to download the latest if available? That would probably preferable as we could keep a "force download latest" button that doesn't care about version checking in case Mozilla moves/changes the archives page.
 3. Or...?

I think I'll start with option 2 for now to keep the changes small and manageable (for myself mostly) and see where we can go from there.

**Comment by krt16s** [comment]
Sorry for not replying farster, real life and fdroid keep me pretty busy. I am not an Android dev my own, i hack on build scripts, not actually app core logic, so I dont mind a junior dev stepping up and doing work. I will try to review and provide feedback (things should get better in 2 weeks) as much as I can.

On the changes: I'd like to keep the current url somhow accesible, just to ensure even minor changes on Mozilla side would break the app. I'd go ahead and first add a second button, then make this button only available when needed (e.g. checked against what is installed) and then move this check (and download) to a service.
