### ISSUE TITLE
Add button "Get it on F-Droid"

### ISSUE THREAD

**Issue by PanderMusubi** [krt16s/ffupdater#3]
Please, add a button "Get it on F-Droid" with a PNG file from https://commons.wikimedia.org/wiki/File:Get_it_on_F-Droid.svg in your README file with the appropriate link to the page of your app on F-Droid.

**Comment by krt16s** [comment]
Anyone who has the app, got it from F-Droid. There is no other official binary source. And given the sad state the app is in, I don't want to advertise it... closing for now, thanks anyway.
