### ISSUE TITLE
only crashes with Android <= 2.3

### ISSUE THREAD

**Issue by guillaume-d** [krt16s/ffupdater#4]
On Android <= 2.3 the app can only crash because the (hardcoded?) HTTPS URL of the Firefox download is not supported by android.app.DownloadManager$Request that your app calls (as Android debug-logs of the app show).

For more details see for example http://stackoverflow.com/questions/24147934/android-download-manager-can-only-download-http-uris or search for "downloadmanager request can only download http uris".

At least users should not be misled: in the worst case you should increase minSdkVersion to >10....

**Comment by krt16s** [comment]
Thanks for reporting. I currently tend to remove what is left of the app and replacing it with a simple Wrapper that generates the download link and sends it as intend to whatever the user might use to download...

**Comment by guillaume-d** [comment]
Is the "Wrapper" still an Android app or some kind of manually installed script?
An autostarting Android app would be nice, a (slim) service (as suggested in #1 AFAICU) even nicer/besser for security updates whereever reboots are less frequent than Firefox updates! ;)

**Comment by krt16s** [comment]
It's still an app but it does not do more than a link to the download uri to the homescreen would do. I planned using services, but me having little time and Mozilla constantly changing their infrastructure let to this stripped down version. I just hope Mozilla enables release channel updates soon.

Could you test the current 45.0.1 version (should be in F-Droid now) on your 2.3 device?

**Comment by guillaume-d** [comment]
It worked perfectly, thank you!
